[versions]
# Plugins
agp = "8.2.2"
dependencyAnalysis = "1.30.0"
dependencyGuard = "0.5.0"
dependencyVersions = "0.51.0"
detekt = "1.23.5"
doctor = "0.9.2"
hilt = "2.51"
javax-inject = "1"
kotlin = "1.9.22"
kover = "0.7.6"
ksp = "1.9.22-1.0.17"
ktlint-cli = "1.2.1"
ktlint-gradle = "12.1.0"
licensee = "1.9.1"
spotless = "6.25.0"
turtle = "0.9.0"

# Libraries
alakazam = "4.4.0"
android-desugaring = "1.1.5"
androidx-activity = "1.8.2"
androidx-compose-bom = "2024.02.02"
androidx-compose-compiler = "1.5.10"
androidx-compose-hilt = "1.0.0"
androidx-coreKtx = "1.12.0"
androidx-navigation = "2.7.0"
java-inject = "1"
kotlinx-coroutines = "1.8.0"
kotlinx-datetime = "0.5.0"
kotlinx-immutable = "0.5.0"
kotlinx-serialization = "1.6.3"
okhttp = "4.12.0"
retrofit-core = "2.9.0"
retrofit-serialization = "1.0.0"
timber = "5.0.1"

# Testing
test-androidx-arch = "2.2.0"
test-androidx-coreKtx = "1.5.0"
test-androidx-junit = "1.1.5"
test-androidx-rules = "1.5.0"
test-androidx-runner = "1.5.2"
test-junit = "4.13.2"
test-mockk = "1.13.7"
test-robolectric = "4.11.1"
test-turbine = "1.0.0"

[libraries]
# Plugins
plugin-agp = { module = "com.android.tools.build:gradle", version.ref = "agp" }
plugin-detekt = { module = "io.gitlab.arturbosch.detekt:detekt-gradle-plugin", version.ref = "detekt" }
plugin-hilt = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "hilt" }
plugin-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
plugin-kover = { module = "org.jetbrains.kotlinx:kover-gradle-plugin", version.ref = "kover" }
plugin-ksp = { module = "com.google.devtools.ksp:com.google.devtools.ksp.gradle.plugin", version.ref = "ksp" }
plugin-ktlint = { module = "org.jlleitschuh.gradle:ktlint-gradle", version.ref = "ktlint-gradle" }
plugin-licensee = { module = "app.cash.licensee:licensee-gradle-plugin", version.ref = "licensee" }
plugin-spotless = { module = "com.diffplug.spotless:spotless-plugin-gradle", version.ref = "spotless" }
plugin-turtle = { module = "com.lordcodes.turtle:turtle", version.ref = "turtle" }

# Libraries
alakazam-android-compose = { module = "dev.jonpoulton.alakazam:android-ui-compose", version.ref = "alakazam" }
alakazam-android-core = { module = "dev.jonpoulton.alakazam:android-core", version.ref = "alakazam" }
alakazam-di-hilt = { module = "dev.jonpoulton.alakazam:di-hilt", version.ref = "alakazam" }
alakazam-kotlin-compose-annotations = { module = "dev.jonpoulton.alakazam:kotlin-compose-annotations", version.ref = "alakazam" }
alakazam-kotlin-core = { module = "dev.jonpoulton.alakazam:kotlin-core", version.ref = "alakazam" }
alakazam-kotlin-time = { module = "dev.jonpoulton.alakazam:kotlin-time", version.ref = "alakazam" }
android-desugaring = { module = "com.android.tools:desugar_jdk_libs", version.ref = "android-desugaring" }
androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "androidx-compose-bom" }
androidx-compose-activity = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-compose-foundation = { module = "androidx.compose.foundation:foundation" }
androidx-compose-hilt = { module = "androidx.hilt:hilt-navigation-compose", version.ref="androidx-compose-hilt" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3" }
androidx-compose-navigation = { module = "androidx.navigation:navigation-compose", version.ref="androidx-navigation" }
androidx-compose-runtime = { module = "androidx.compose.runtime:runtime" }
androidx-compose-uiTooling = { module = "androidx.compose.ui:ui-tooling" }
androidx-compose-uiToolingPreview = { module = "androidx.compose.ui:ui-tooling-preview" }
androidx-coreKtx = { module = "androidx.core:core-ktx", version.ref = "androidx-coreKtx" }
androidx-navigation-commonKtx = { module = "androidx.navigation:navigation-common-ktx", version.ref = "androidx-navigation" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt" }
javax-inject = { module = "javax.inject:javax.inject", version.ref = "javax-inject" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }
kotlinx-immutable = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version.ref = "kotlinx-immutable" }
kotlinx-serialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "kotlinx-serialization" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
retrofit-core = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit-core" }
retrofit-serialization = { module = "com.jakewharton.retrofit:retrofit2-kotlinx-serialization-converter", version.ref = "retrofit-serialization" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }

# Testing
test-alakazam-core = { module = "dev.jonpoulton.alakazam:testing-core", version.ref = "alakazam" }
test-androidx-arch = { module = "androidx.arch.core:core-testing", version.ref = "test-androidx-arch" }
test-androidx-coreKtx = { module = "androidx.test:core-ktx", version.ref = "test-androidx-coreKtx" }
test-androidx-junit = { module = "androidx.test.ext:junit", version.ref = "test-androidx-junit" }
test-androidx-rules = { module = "androidx.test:rules", version.ref = "test-androidx-rules" }
test-androidx-runner = { module = "androidx.test:runner", version.ref = "test-androidx-runner" }
test-junit = { module = "junit:junit", version.ref = "test-junit" }
test-kotlin-common = { module = "org.jetbrains.kotlin:kotlin-test-common", version.ref = "kotlin" }
test-kotlin-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }
test-kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
test-mockk-core = { module = "io.mockk:mockk", version.ref = "test-mockk" }
test-mockk-android = { module = "io.mockk:mockk-android", version.ref = "test-mockk" }
test-robolectric = { module = "org.robolectric:robolectric", version.ref = "test-robolectric" }
test-turbine = { module = "app.cash.turbine:turbine", version.ref = "test-turbine" }

[plugins]
agp-app = { id = "com.android.application", version.ref = "agp" }
agp-lib = { id = "com.android.library", version.ref = "agp" }
dependencyGuard = { id = "com.dropbox.dependency-guard", version.ref = "dependencyGuard" }
dependencyAnalysis = { id = "com.autonomousapps.dependency-analysis", version.ref = "dependencyAnalysis" }
dependencyVersions = { id = "com.github.ben-manes.versions", version.ref = "dependencyVersions" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
doctor = { id = "com.osacky.doctor", version.ref = "doctor" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint-gradle" }
licensee = { id = "app.cash.licensee", version.ref = "licensee" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
