services:
  base:
#    build:
#      context: ..
#      dockerfile: docker/Dockerfile
    image: ghcr.io/jonapoul/actual-android:latest
    volumes:
      - $HOME/.gradle:/home/gradle/.gradle
      - ..:/project
    working_dir: /project

  check:
    extends: base
    command: /bin/bash -c "gradle -Dorg.gradle.java.home=/opt/java/openjdk/ check"

  koverLog:
    extends: base
    command: /bin/bash -c "gradle -Dorg.gradle.java.home=/opt/java/openjdk/ koverLog"
