services:
  base:
#    build:
#      context: ..
#      dockerfile: docker/Dockerfile
    image: ghcr.io/jonapoul/actual-android:latest
    volumes:
      - ${ANDROID_HOME}:${ANDROID_HOME}
      - ./:/workspace
      - ~/.gradle:/root/.gradle
    environment:
      - ANDROID_HOME=${ANDROID_HOME}
    working_dir: /workspace

  check:
    extends: base
    command: /bin/bash -c "gradle -Dorg.gradle.java.home=/opt/java/openjdk/ check"

  koverLog:
    extends: base
    command: /bin/bash -c "gradle -Dorg.gradle.java.home=/opt/java/openjdk/ koverLog"
