name: Main

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write
  checks: write

concurrency:
  group: 'ci-${{ github.event.merge_group.head_ref || github.head_ref }}-${{ github.workflow }}'
  cancel-in-progress: true

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v5
        with:
          add-job-summary: on-failure

      - name: Run tests
        run: |
          docker run --rm \
            -v "{$PWD}:/project" \
            -v "{$HOME}/.gradle":/root/.gradle \
            -w /project \
            gradle:9.1.0-jdk21 \
            gradle :koverLog | tee kover-report.txt

      - name: Fix permissions
        run: sudo chown -R runner:runner .
        if: ${{ !cancelled() }}

      - name: Parse coverage
        shell: bash
        run: |
          COVERAGE=$(cat kover-report.txt | grep "application line coverage:" | tail -n1 | cut -d ":" -f 2 | tr -d '[:space:]%')
          echo "COVERAGE=$(echo $COVERAGE)" >> $GITHUB_ENV

      - name: Update dynamic badge gist
        uses: schneegans/dynamic-badges-action@v1.7.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: 6bf1b7a292bc61bcca966bee22e8b456
          filename: coverage-badge.json
          label: coverage
          message: ${{ env.COVERAGE }}%
          valColorRange: ${{ env.COVERAGE }}
          minColorRange: 0
          maxColorRange: 100

      - name: Report build results
        uses: gmazzo/publish-report-annotations@v1
        if: ${{ !cancelled() }}
