name: PR

on:
  pull_request:

env:
  CI: true

permissions:
  contents: read
  pull-requests: write

concurrency:
  group: 'ci-${{ github.event.merge_group.head_ref || github.head_ref }}-${{ github.workflow }}'
  cancel-in-progress: true

jobs:
  pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v5
        with:
          add-job-summary: on-failure

      - name: Check
        run: |
          docker run --rm \
            -v $PWD:/project \
            -v $HOME/.gradle:/root/.gradle \
            -w /project \
            gradle:9.1.0-jdk21 \
            gradle check

      - name: Report build results
        uses: gmazzo/publish-report-annotations@v1
        if: ${{ !cancelled() }}
