name: PR Check

on:
  pull_request:
    branches:

permissions:
  contents: write
  checks: write

jobs:
  pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: 19
          distribution: "zulu"

      - name: Add permissions
        run: chmod +x ./gradlew

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          generate-job-summary: false
          cache-read-only: true

      - name: Check
        run: ./gradlew check koverHtmlReport

      - name: Generate coverage report
        run: ./gradlew koverXmlReport

      - name: Read coverage
        run: echo "COVERAGE=$(./gradlew -q printInstructionCoverage)" >> $GITHUB_ENV

      - name: Upload reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: reports
          path: |
            ./*/build/reports
            ./build/reports
          if-no-files-found: error

      - name: Publish test reports
        uses: mikepenz/action-junit-report@v4
        if: always()
        with:
          report_paths: "**/build/test-results/*/TEST-*.xml"

      - name: Update dynamic badge gist
        uses: schneegans/dynamic-badges-action@v1.7.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: 771fc7b1a375f223a36f740c5c2695d3
          filename: actual-coverage-badge.json
          label: coverage
          message: ${{ env.COVERAGE }}%
          valColorRange: ${{ env.COVERAGE }}
          minColorRange: 0
          maxColorRange: 100
