name: PR

on:
  pull_request:

env:
  CI: true

permissions:
  contents: read
  pull-requests: write

concurrency:
  group: 'ci-${{ github.event.merge_group.head_ref || github.head_ref }}-${{ github.workflow }}'
  cancel-in-progress: true

jobs:
  pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          fetch-tags: true
          ref: ${{ github.head_ref }}

      - name: Setup JDK
        uses: actions/setup-java@v5
        with:
          java-version-file: .github/workflows/.java-version
          distribution: "zulu"

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v5
        with:
          add-job-summary: on-failure
          cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}

      - name: Check
        run: ./gradlew check

      - name: Report build results
        uses: gmazzo/publish-report-annotations@v1
        if: ${{ !cancelled() }}
