name: Validate Workflows

on:
  push:
    paths:
      - ".github/workflows/**"

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Lint actions
        uses: raven-actions/actionlint@v2
